language: php
cache:
  directories:
    - "$HOME/.composer/cache"
matrix:
  include:
##--- PHP 7.1 ---##
    - php: 7.1
      env: LARAVEL=5.5
    - php: 7.1
      env: LARAVEL=5.5 TEST_DB_ENGINE=mysql
    - php: 7.1
      env: LARAVEL=5.5 TEST_DB_ENGINE=pgsql
    - php: 7.1
      env: LARAVEL=5.6
    - php: 7.1
      env: LARAVEL=5.7
    - php: 7.1
      env: LARAVEL=5.8
##--- PHP 7.2 ---##
    - php: 7.2
      env: LARAVEL=5.5
    - php: 7.2
      env: LARAVEL=5.6
    - php: 7.2
      env: LARAVEL=5.7
    - php: 7.2
      env: LARAVEL=5.8
    - php: 7.2
      env: LARAVEL=6.0
##--- PHP 7.3 ---##
    - php: 7.3
      env: LARAVEL=5.5
    - php: 7.3
      env: LARAVEL=5.6
    - php: 7.3
      env: LARAVEL=5.7
    - php: 7.3
      env: LARAVEL=5.7 TEST_DB_ENGINE=mysql
    - php: 7.3
      env: LARAVEL=5.7 TEST_DB_ENGINE=pgsql
    - php: 7.3
      env: LARAVEL=5.8
    - php: 7.3
      env: LARAVEL=5.8 TEST_DB_ENGINE=mysql
    - php: 7.3
      env: LARAVEL=5.8 TEST_DB_ENGINE=pgsql
    - php: 7.3
      env: LARAVEL=6.5
    - php: 7.3
      env: LARAVEL=6.5 TEST_DB_ENGINE=mysql
    - php: 7.3
      env: LARAVEL=6.5 TEST_DB_ENGINE=pgsql
script:
  - vendor/bin/phpunit --testdox
before_install:
  - MINOR=`echo $LARAVEL | sed 's/[5|6]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]$ ]] && MAJOR=6 || MAJOR=5'
  - '[ 6 -eq $MAJOR ] && ORCH=4 || ORCH=3'
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'mysql' = $TEST_DB_ENGINE ] && mysql -e 'DROP DATABASE IF EXISTS customer_test;CREATE DATABASE customer_test;'" || true
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'pgsql' = $TEST_DB_ENGINE ] && psql -c 'create database customer_test;' -U postgres" || true
install: composer install --no-interaction
services:
  - mysql
  - postgresql
notifications:
  email: false
  slack:
    rooms:
      secure: hA1g+8HQmGDe7ERVPPBL+bWK4nqOwXkYc2NxL4cSvcM92EZJGy7LyREMPkpEuTrNak13BQDe8kyChf/znL2CrC1i95TW2hopawO4sst+JhlqKmoqo+UE5wpWijRBKJIIffL1S44nx3VH4ETEq+8GSbHeI8RAi2QCNgQbDzDEA52B324+22h0su51Ix4Jvzl1EHNP+SiChTbmG+XprY7FGX0860CR/nj236ghxJ+n6jjeu7cz/YW7BgVNv4WZdjOGQ/20fjAJ/VnM0r1nzvK1oAfkAlkbMpICn3KR79e4fHzNXOygSarF0BJEW57drDoyGqQU1XThwHKX6MhWyv3F8Kv6i8AfZUziIM7Bt3Q0jK8bgb465KuiMf3bhMeFxkiRI72rnZlD9IgtlXjSii2RLbIguagZcvIIz512QO0VqAOPLpvtGXGM1kWVsiUeGOkGAsToYvSKOH1+obxXSA87+iDcuvTzYyXnnytftDZ1jle03i19mjqN6dBSDrxrX4IeyFl5yDDG57ajPuUnPGmN6va/N01yAJHwbNGM7HH+/MmwEJkkBEquyCNxpN+aza+UE9Of5uDwEpA/vEAy23JjUB2AmB2j9aBcwBqvAhnU/ujpboinWiSi2xigGJ+r2ggsZzMSPik3dQE1/wqQPRmLVzgU3STXTwkuQZGDs75hZSQ=
